const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('autoflow', {
  record: () => ipcRenderer.send('record'),
  stop: () => ipcRenderer.send('stop'),
  loop: () => ipcRenderer.send('loop'),
  save: () => ipcRenderer.send('save'),
  load: () => ipcRenderer.send('load'),
  setSpeed: (speed) => ipcRenderer.send('set-speed', speed),
  setRepeat: (count) => ipcRenderer.send('set-repeat', count),
  setHumanize: (val) => ipcRenderer.send('set-humanize', val),
  setStartDelay: (val) => ipcRenderer.send('set-start-delay', val),
  setExpanded: (expanded) => ipcRenderer.send('set-expanded', expanded),
  getBuildInfo: () => ipcRenderer.invoke('get-build-info'),
  getTrialStatus: () => ipcRenderer.invoke('get-trial-status'),
  getLicenseStatus: () => ipcRenderer.invoke('license-status'),
  activateLicense: (key) => ipcRenderer.invoke('activate-license', key),
  notifyLicenseActivated: () => ipcRenderer.send('license-activated-ui'),
  close: () => ipcRenderer.send('close-app'),
  minimize: () => ipcRenderer.send('minimize'),
  togglePin: () => ipcRenderer.send('toggle-pin'),
  getScripts: () => ipcRenderer.send('get-scripts'),
  saveScript: (name) => ipcRenderer.send('save-script', name),
  loadScript: (name) => ipcRenderer.send('load-script', name),
  deleteScript: (name) => ipcRenderer.send('delete-script', name),
  renameScript: (oldName, newName) => ipcRenderer.send('rename-script', oldName, newName),
  getHotkeys: () => ipcRenderer.send('get-hotkeys'),
  setHotkey: (which, vk) => ipcRenderer.send('set-hotkey', which, vk),
  captureHotkey: (which) => ipcRenderer.send('capture-hotkey', which),
  cancelCapture: () => ipcRenderer.send('cancel-capture'),
  onHotkeysUpdated: (cb) => ipcRenderer.on('hotkeys-updated', (_e, data) => cb(data)),
  onHotkeyCaptured: (cb) => ipcRenderer.on('hotkey-captured', (_e, which) => cb(which)),
  onScriptsUpdated: (cb) => ipcRenderer.on('scripts-updated', (_e, scripts) => cb(scripts)),
  onStateChanged: (cb) => ipcRenderer.on('state-changed', (_e, s) => cb(s)),
  onApiError: (cb) => ipcRenderer.on('api-error', (_e, msg) => cb(msg)),
  onActionCount: (cb) => ipcRenderer.on('action-count', (_e, n) => cb(n)),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, msg) => cb(msg)),
  onPinChanged: (cb) => ipcRenderer.on('pin-changed', (_e, pinned) => cb(pinned)),
  onRepeatStatus: (cb) => ipcRenderer.on('repeat-status', (_e, status) => cb(status)),
  onTrialStatus: (cb) => ipcRenderer.on('trial-status', (_e, status) => cb(status)),
});
